name: PyInstaller

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]


jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
    
    - name: Instala las dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Instala weas de OpenGL
      run: |
        curl -LJO https://github.com/pal1000/mesa-dist-win/releases/download/19.1.0/mesa3d-19.1.0-release-msvc.exe
        7z x mesa3d-19.1.0-release-msvc.exe
        cd x64
        xcopy opengl32.dll C:\windows\system32\mesadrv.dll*
        xcopy opengl32.dll C:\windows\syswow64\mesadrv.dll*
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\OpenGLDrivers\MSOGL" /v DLL /t REG_SZ /d "mesadrv.dll" /f
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\OpenGLDrivers\MSOGL" /v DriverVersion /t REG_DWORD /d 1 /f
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\OpenGLDrivers\MSOGL" /v Flags /t REG_DWORD /d 1 /f
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\OpenGLDrivers\MSOGL" /v Version /t REG_DWORD /d 2 /f
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\OpenGLDrivers\MSOGL" /v DLL /t REG_SZ /d "mesadrv.dll" /f
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\OpenGLDrivers\MSOGL" /v DriverVersion /t REG_DWORD /d 1 /f
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\OpenGLDrivers\MSOGL" /v Flags /t REG_DWORD /d 1 /f
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\OpenGLDrivers\MSOGL" /v Version /t REG_DWORD /d 2 /f
    
    - name: Utiliza PyInstaller
      run: |
        pyinstaller --onefile -i "Logo.ico" Codigo_fuente.py
    
    - uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Añade el .exe automáticamente

        # Optional name of the branch the commit should be pushed to
        # Required if Action is used in Workflow listening to the `pull_request` event.
        # Also required for almost all other events (eg. `schedule`)
        branch: ${{ github.head_ref }}

        # Optional git params
        commit_options: '--no-verify --signoff'

        # Optional glob pattern of files which should be added to the commit
        file_pattern: dist/*.exe

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: My GitHub Actions Bot
        commit_user_email: my-github-actions-bot@example.org
        commit_author: Author <actions@github.com>

        # Optional tag message. 
        # Action will create and push a new tag to the remote repository and the defined branch
        tagging_message: 'v1.0.0'
